# Creating a Docker container action - https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

name: "bm-sonarscan-dotnet"
description: "SonarScanner for .NET."
author: "BMIvan"

# branding.icon - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#brandingicon
# white, yellow, blue, green, orange, red, purple, gray-dark
branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  sonarProjectKey: # id of input
    description: "The key of the SonarQube project"
    required: true

  sonarProjectName:
    description: "The name of the SonarQube project"
    required: true

  sonarOrganization:
    description: "The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting."
    required: false

  dotnetBuildArguments:
    description: "Optional command arguments to 'dotnet build'"
    required: false

  dotnetPreBuildCmd:
    description: "Optional command run before the 'dotnet build'"
    required: false

  dotnetTestArguments:
    description: "Optional command arguments to 'dotnet test'"
    required: false

  dotnetDisableTests:
    description: "Optional. Set to 1 or true to not run 'dotnet test' command"
    required: false

  sonarBeginArguments:
    description: "Optional extra command arguments the the SonarScanner 'begin' command"
    required: false

  sonarHostname:
    description: "The SonarQube server URL. For SonarCloud, skip this setting."
    default: "https://sonarcloud.io"
    required: false

outputs:
  html_url:
    description: 'SonarCloud Code Analysis html url'

runs:
  using: "docker"
  image: "Dockerfile"
